/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { lookupLookup } from "../../funcs/lookupLookup.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  customerUuid: z.string(),
  phoneNumber: z.string(),
  type: z.array(operations.Type$inboundSchema).optional(),
};

export const tool$lookupLookup: ToolDefinition<typeof args> = {
  name: "lookup-lookup",
  description: `Look up for phone number`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await lookupLookup(
      client,
      args.customerUuid,
      args.phoneNumber,
      args.type,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
