/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { otpFeedback } from "../../funcs/otpFeedback.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.FeedbackRequest$inboundSchema.optional(),
};

export const tool$otpFeedback: ToolDefinition<typeof args> = {
  name: "otp-feedback",
  description: `Send feedback

Send feedback about the authentication process.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await otpFeedback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
