workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/ding-live/openapi/main/ding.yaml
targets:
    '@ding-live/ding':
        target: typescript
        source: my-source
        publish:
            npm:
                token: $NPM_TOKEN
