/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

export type CheckResponse =
  | components.CreateCheckResponse
  | components.ErrorResponse;

/** @internal */
export const CheckResponse$inboundSchema: z.ZodType<
  CheckResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.CreateCheckResponse$inboundSchema,
  components.ErrorResponse$inboundSchema,
]);

/** @internal */
export type CheckResponse$Outbound =
  | components.CreateCheckResponse$Outbound
  | components.ErrorResponse$Outbound;

/** @internal */
export const CheckResponse$outboundSchema: z.ZodType<
  CheckResponse$Outbound,
  z.ZodTypeDef,
  CheckResponse
> = z.union([
  components.CreateCheckResponse$outboundSchema,
  components.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckResponse$ {
  /** @deprecated use `CheckResponse$inboundSchema` instead. */
  export const inboundSchema = CheckResponse$inboundSchema;
  /** @deprecated use `CheckResponse$outboundSchema` instead. */
  export const outboundSchema = CheckResponse$outboundSchema;
  /** @deprecated use `CheckResponse$Outbound` instead. */
  export type Outbound = CheckResponse$Outbound;
}
