/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

export type RetryResponse =
  | components.ErrorResponse
  | components.RetryAuthenticationResponse;

/** @internal */
export const RetryResponse$inboundSchema: z.ZodType<
  RetryResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.ErrorResponse$inboundSchema,
  components.RetryAuthenticationResponse$inboundSchema,
]);

/** @internal */
export type RetryResponse$Outbound =
  | components.ErrorResponse$Outbound
  | components.RetryAuthenticationResponse$Outbound;

/** @internal */
export const RetryResponse$outboundSchema: z.ZodType<
  RetryResponse$Outbound,
  z.ZodTypeDef,
  RetryResponse
> = z.union([
  components.ErrorResponse$outboundSchema,
  components.RetryAuthenticationResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RetryResponse$ {
  /** @deprecated use `RetryResponse$inboundSchema` instead. */
  export const inboundSchema = RetryResponse$inboundSchema;
  /** @deprecated use `RetryResponse$outboundSchema` instead. */
  export const outboundSchema = RetryResponse$outboundSchema;
  /** @deprecated use `RetryResponse$Outbound` instead. */
  export type Outbound = RetryResponse$Outbound;
}
