/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A status representing the result of the check.
 */
export enum CreateCheckResponseStatus {
    Valid = "valid",
    Invalid = "invalid",
    WithoutAttempt = "without_attempt",
    RateLimited = "rate_limited",
    AlreadyValidated = "already_validated",
    ExpiredAuth = "expired_auth",
}

export class CreateCheckResponse extends SpeakeasyBase {
    /**
     * The UUID of the corresponding authentication.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "authentication_uuid" })
    authenticationUuid?: string;

    /**
     * A status representing the result of the check.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: CreateCheckResponseStatus;
}
